name: 1a Hola mundo
on:
  workflow_dispatch:
  push:
jobs:
  # This workflow contains a single job called "greet"
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola Mundo
      run: echo "Hola  Mundo"
