name: 04a - Distintas shells

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bash
        shell: bash
        run: echo $0
      - name: sh
        shell: sh
        run: echo $0
      - name: Por defecto
        run: echo $0
