name: 04b - instalar Paquetes
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout node version
        run: node --version
      - name: Install jsonlint
        run: |
          sudo apt-get update
          sudo apt-get install jsonlint
      - name: Lint json
        run: jsonlint-php package.json
