name: 05b - Check runners
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  expresiones:
    runs-on: ubuntu-latest
    steps:
      - name: Runner Info
        id: runnerInfo
        run: echo "${{toJson(runner)}}"
      - name: Runner Arch
        id: runnerArch
        run: echo "${{toJson(runner.arch)}}"
