name: 07b - Entrada y salida con resumen

on:
  workflow_dispatch:
    inputs:
      numero-dados:
        type: choice
        options:
          - uno
          - dos
        default: dos
        description: El número de dados
jobs:
  tirada-dados:
    outputs:
      dado1: ${{ steps.dado1.outputs.dado1 }}
      dado2: ${{ steps.dado2.outputs.dado2 }}
    runs-on: ubuntu-latest
    steps:
      - name: ¿Cuántos dados?
        run: echo "Hay ${{inputs.numero-dados}} dados"
      - name: Generar Dado 1
        id: dado1
        run: echo "dado1=$((1 + RANDOM % 6))" >> "$GITHUB_OUTPUT"
      - name: Generar Dado 2
        if: ${{ inputs.numero-dados == 'dos' }}
        id: dado2
        run: echo "dado2=$((1 + RANDOM % 6))" >> "$GITHUB_OUTPUT"
  resumen:
    runs-on: ubuntu-latest
    needs: tirada-dados
    steps:
      - name: Resumen de las salidas un dado
        if: ${{ inputs.numero-dados == 'uno' }}
        run: |
          echo "dado 1 : ${{needs.tirada-dados.outputs.dado1}}"
      - name: Resumen de las salidas dos dados
        if: ${{ inputs.numero-dados == 'dos' }}
        run: |
          echo "dado 1 : ${{needs.tirada-dados.outputs.dado1}}"
          echo "dado 2 : ${{needs.tirada-dados.outputs.dado2}}"
